Invoke Monkey Patching for All Tests
Eventlet 0.20.x adds support for monkey patching 'subprocess' and
drops 'select.poll'. So, when 'select' is patched and 'subproces'
is not, which is how Glance moneky patches for eventlet, following
errors show up.
"AttributeError: module 'select' has no attribute 'poll'".

Thus, to fix the errors I4de03e2a1ca493cd49a474a67cbbdec24d61b98f
attempted to green the tests to support eventlet 0.20.x.
However, that covered only functional tests causing other tests to
fail. This change monkey patches for eventlet right in 'glance.tests`
pacakge so that all tests are covered.

Closes-Bug: #1655727
Change-Id: Ice3d431ac0c8ece97471abced9ae2d5ad2be261d