Avoid TestClient error on missing '__mro__' attr
The TestClient unit test fails with:

   AttributeError: class Zeros has no attribute '__mro__'

on Python 2.6 running on Ubuntu Lucid.

Resolve by defining Zeros as a new-style class.

Change-Id: I97f8eaac31d34a68613e9b30a177191a9de281b0