Image conversion fails
It is not possible to convert glance images as it fails with error,
NoSuchOptError: no such option 'conversion_plugin_options' in group
[DEFAULT] as there is no 'conversion_plugin_options' option or group
in glance-image-import.conf file.

Used correct option group 'image_conversion' to fetch the image
'output_format' option.

Change-Id: Ia7ced170bcddcd3639b7edfb644deef3018b11a8
Closes-Bug: #1805765
(cherry picked from commit 8ee37b7d7ca7d5d2d5e8ef2adc61306f3b57a0a2)