Fix manpage building and remove glance-cache-manage
Commit f126d3b8cc6ea5b8dc removed glancecachemanage.rst . So man page
building (which is not tested in CI) is broken and the failure when
building with:

sphinx-build -W -b man doc/source doc/build/man

is:

[snipped]
writing... glance-api.1 { } glance-cache-cleaner.1 { } glance-cache-manage.1 {
Exception occurred:
[snipped]
IOError: [Errno 2] No such file or directory: \
    u'/openstack/glance/doc/build/man/.doctrees/cli/glancecachemanage.doctree'

Change-Id: I07471cdf472789bd149746a687484420a4b8675f
Closes-Bug: #1840424