Sync iso8601 requirement and fixes test case failures
1. Sync requirements from global Iece0116d3c412216251e2d7fbffe10bfe2c1c789
2. iso8601>=0.1.7 "parse_date()" could successfully handle date string
which only have date part like YYYY-MM-DD, it caused two Glance test
cases failure.

Fixes bug: 1242501

Grizzly notice: this should fix stable/grizzly tempest failure
 error: Installed distribution iso8601 0.1.4 conflicts with requirement iso8601>=0.1.8
 at the expense of bumping version requirement for iso8601 on stable branch!

Also incldues: Pin Sphinx to <1.2

1.2 was just released and has a bug that causes builds to fail with
the error:

  error: 'source_dir' must be a directory name (got `...doc/source`)

Fixes bug: 1259511

See: http://bugs.python.org/issue19570
and: https://bitbucket.org/birkenfeld/sphinx/pull-request/193/builddoc-shouldnt-
fail-on-unicode-paths/diff

Change-Id: I2625eb3888111829a9da4d093b34193b8795f264
Signed-off-by: Zhi Yan Liu <zhiyanl@cn.ibm.com>
(cherry picked from commit 8160ae293383ec600c05fd2e4b38164bca7704c4)
Conflicts:
        glance/tests/unit/v1/test_api.py
        glance/tests/unit/v1/test_registry_api.py
        tools/pip-requires